server:
  port: 9264
  
spring:
  datasource:
    url: jdbc:mariadb://192.168.33.133:3306/easy_wf?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: mysql
    driverClassName: org.mariadb.jdbc.Driver
  hikari:
    minimum-idle: 1
    maximum-pool-size: 10
  jpa:
    format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
logging:
  level:
    root: INFO
  file: log/logfile.log
easywf:
  org-rule: base-org-rule
#  此方式支持自定义， 也可通过primary注解指定
